### PR TITLE
update to mosn.io/api v1.2.3

### PR DESCRIPTION
**Pull request by taoyuanyuan**

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
Screenshot 2022-11-02 at 1 55 13 PM

"test" I think you need to delete manually from settings like this @taoyuanyuan

**Comment by codefromthecrypt** [comment]
Screenshot 2022-11-02 at 1 56 34 PM


click edit, then delete the stale rule I mean.

**Review by antJack — APPROVED** [review]
LGTM

**Comment by taoyuanyuan** [comment]
> Screenshot 2022-11-02 at 1 55 13 PM
> 
> "test" I think you need to delete manually from settings like this @taoyuanyuan

@codefromthecrypt  thank you!

**Pull request merged**
