### PR TITLE
Adds a build matrix for supported Go versions

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This also lowers go.mod to 1.17 accordingly

cc @taoyuanyuan @antJack

See mosn/mosn#2153

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
@taoyuanyuan once this is in, can you help cut api and pkg versions? then I can go and do holmes, proxy-host etc, instead of doing twice (once for go then again for api/pkg)

**Comment by antJack** [comment]
any idea about this blocking workflow?

**Comment by codefromthecrypt** [comment]
@antJack so it expects the same workflow to pass, exactly by name. but now that there is a matrix, the name has a dimension of the go version. So the "test" will never pass in this PR. This is a glitch in how GitHub sets up expectations, but it will go away after merge because then the "test" with the dimension name are expected and without isn't.

**Review by antJack — APPROVED** [review]
LGTM

**Comment by taoyuanyuan** [comment]
@codefromthecrypt we have released v1.2.2, thank you~

**Comment by codefromthecrypt** [comment]
@taoyuanyuan oops we are not aligned because pkg is not using the release version of api. can you recut both to be sync maybe 1.2.3? https://github.com/mosn/pkg/blob/master/go.mod

**Comment by taoyuanyuan** [comment]
> @antJack so it expects the same workflow to pass, exactly by name. but now that there is a matrix, the name has a dimension of the go version. So the "test" will never pass in this PR. This is a glitch in how GitHub sets up expectations, but it will go away after merge because then the "test" with the dimension name are expected and without isn't.

@codefromthecrypt   I see the "test" still exists   https://github.com/mosn/pkg/pull/69

**Comment by codefromthecrypt** [comment]
@taoyuanyuan I don't have access but I think you can check like here https://github.com/mosn/pkg/settings/branch_protection_rules

**Comment by taoyuanyuan** [comment]
@codefromthecrypt  we have released v1.2.3,  go on~

**Pull request merged**
